# Generated by Django 3.2.4 on 2021-07-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210703_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Expired', 'Expired'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Denied', 'Denied')], default='Available', max_length=10),
        ),
    ]
